name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "19", "20"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
